name: ClickUp Task Notifier

on:
  schedule:
    - cron: '20 3 * * 0-4'  # Run at 09:20 AM BDT (03:20 UTC) Sunday to Thursday
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run notification script
        env:
          CLICKUP_API_KEY: ${{ secrets.CLICKUP_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py